### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by andrew-stclair** [metatoaster/kanna#2]
not really an issue, just tested this in windows and it error'd complaining about missing curses. curses does not exist on windows at all.

you may wish to mention this in the readme

**Comment by metatoaster** [comment]
Do you happen to have Windows 10 and have the WSL (Windows Subsystem for Linux) available?  If not I can see if I can get someone to test this for me so I can update the blurb in the readme on what this was tested under.

**Comment by andrew-stclair** [comment]
I do have access to a win 10 computer with the Linux sub system installed, ill test that and get back to you
